name: build

on:
  push:
    branches: [ "main", "test" ]

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      openapi: ${{ steps.filter.outputs.openapi }}
      mobi: ${{ steps.filter.outputs.mobi }}
      mobi-web: ${{ steps.filter.outputs.mobi-web }}
      manage: ${{ steps.filter.outputs.manage }}
      manage-web: ${{ steps.filter.outputs.manage-web }}
      task: ${{ steps.filter.outputs.task }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Check changed paths
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            openapi:
              - 'app/openapi/**'
              - 'lib/**'
            mobi:
              - 'app/mobi/**'
              - 'lib/**'
            mobi-web:
              - 'app/mobi-web/**'
              - 'app/mobi-web/public/.well-known/**'
              - 'lib/common/**'
            manage:
              - 'app/manage/**'
              - 'lib/**'
            manage-web:
              - 'app/manage-web/**'
              - 'lib/common/**'
            task:
              - 'app/task/**'
              - 'lib/**'
            

  build-openapi:
    needs: changes
    if: ${{ needs.changes.outputs.openapi == 'true' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Build Value
        id: build
        run: |
          echo "short_sha=${GITHUB_SHA:0:7}" >> $GITHUB_OUTPUT
          echo "timestamp=$(date +%Y%m%d%H%M%S)" >> $GITHUB_OUTPUT
          echo "branch=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT

      - name: Build and push mobi
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./app/openapi/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/video-mobi/openapi:${{ steps.build.outputs.branch }}-${{ steps.build.outputs.timestamp }}-${{ steps.build.outputs.short_sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  build-mobi:
    needs: changes
    if: ${{ needs.changes.outputs.mobi == 'true' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Build Value
        id: build
        run: |
          echo "short_sha=${GITHUB_SHA:0:7}" >> $GITHUB_OUTPUT
          echo "timestamp=$(date +%Y%m%d%H%M%S)" >> $GITHUB_OUTPUT
          echo "branch=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT

      - name: Build and push mobi
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./app/mobi/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/video-mobi/mobi:${{ steps.build.outputs.branch }}-${{ steps.build.outputs.timestamp }}-${{ steps.build.outputs.short_sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  build-mobi-web:
    needs: changes
    if: ${{ needs.changes.outputs.mobi-web == 'true' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Enable corepack
        run: corepack enable

      - name: Build App
        run: |
          pnpm install
          pnpm build:mobi-web

      - name: Get Build Value
        id: build
        run: |
          echo "short_sha=${GITHUB_SHA:0:7}" >> $GITHUB_OUTPUT
          echo "timestamp=$(date +%Y%m%d%H%M%S)" >> $GITHUB_OUTPUT
          echo "branch=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT
      
      - name: Upload Artifacts
        uses: actions/upload-artifact@v6
        with:
          name: video-mobi-web-${{ steps.build.outputs.branch }}-${{ steps.build.outputs.timestamp }}-${{ steps.build.outputs.short_sha }}
          path: app/mobi-web/dist
          retention-days: 7

  build-manage:
    needs: changes
    if: ${{ needs.changes.outputs.manage == 'true' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Build Value
        id: build
        run: |
          echo "short_sha=${GITHUB_SHA:0:7}" >> $GITHUB_OUTPUT
          echo "timestamp=$(date +%Y%m%d%H%M%S)" >> $GITHUB_OUTPUT
          echo "branch=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT

      - name: Build and push manage
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./app/manage/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/video-mobi/manage:${{ steps.build.outputs.branch }}-${{ steps.build.outputs.timestamp }}-${{ steps.build.outputs.short_sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  build-manage-web:
    needs: changes
    if: ${{ needs.changes.outputs.manage-web == 'true' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Enable corepack
        run: corepack enable

      - name: Build App
        run: |
          pnpm install
          pnpm build:manage-web

      - name: Get Build Value
        id: build
        run: |
          echo "short_sha=${GITHUB_SHA:0:7}" >> $GITHUB_OUTPUT
          echo "timestamp=$(date +%Y%m%d%H%M%S)" >> $GITHUB_OUTPUT
          echo "branch=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT
      
      - name: Upload Artifacts
        uses: actions/upload-artifact@v6
        with:
          name: video-manage-web-${{ steps.build.outputs.branch }}-${{ steps.build.outputs.timestamp }}-${{ steps.build.outputs.short_sha }}
          path: app/manage-web/dist
          retention-days: 7

  build-task:
    needs: changes
    if: ${{ needs.changes.outputs.task == 'true' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Build Value
        id: build
        run: |
          echo "short_sha=${GITHUB_SHA:0:7}" >> $GITHUB_OUTPUT
          echo "timestamp=$(date +%Y%m%d%H%M%S)" >> $GITHUB_OUTPUT
          echo "branch=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT

      - name: Build and push task
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./app/task/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/video-mobi/task:${{ steps.build.outputs.branch }}-${{ steps.build.outputs.timestamp }}-${{ steps.build.outputs.short_sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
